[workspace]
resolver = "2"
members = ["crates/frontend", "crates/backend"]

[workspace.package]
version = "0.1.0"
edition = "2024"
authors = ["{{author}}"]
description = "{{description}}"
license = "{{license}}"
